=== cnorthwood/ternip/data/timebank/TimeML1.1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xml:lang="en"
			version="1.1">

  <xs:annotation>
    <xs:documentation xml:lang="en-us">
      TimeML schema
      <a href="http://www.timeml.org/">TANGO</a>
    </xs:documentation>
  </xs:annotation>

	<xs:simpleType name="TimeMLID">
	    <xs:annotation>
	      <xs:documentation xml:lang="en-us">
		A <b>TimeMLID</b> is a sequence of lowercase letters followed by a number (decimal digits).
	      </xs:documentation>
	    </xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z]+\p{Nd}+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="EventID">
    <xs:annotation>
      <xs:documentation xml:lang="en-us">
        A <b>EventID</b> is an <b>e</b> followed by a number (decimal digits).
      </xs:documentation>
    </xs:annotation>
		<xs:restriction base="TimeMLID">
			<xs:pattern value="e\p{Nd}+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="EventInstanceID">
    <xs:annotation>
      <xs:documentation xml:lang="en-us">
        A <b>EventInstanceID</b> is an <b>ei</b> followed by a number (decimal digits).
      </xs:documentation>
    </xs:annotation>
		<xs:restriction base="TimeMLID">
			<xs:pattern value="ei\p{Nd}+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TimeID">
    <xs:annotation>
      <xs:documentation xml:lang="en-us">
        A <b>TimeID</b> is an <b>t</b> followed by a number (decimal digits).
      </xs:documentation>
    </xs:annotation>
		<xs:restriction base="TimeMLID">
			<xs:pattern value="t\p{Nd}+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="SignalID">
    <xs:annotation>
      <xs:documentation xml:lang="en-us">
        A <b>SignalID</b> is an <b>s</b> followed by a number (decimal digits).
      </xs:documentation>
    </xs:annotation>
		<xs:restriction base="TimeMLID">
			<xs:pattern value="s\p{Nd}+" />
		</xs:restriction>
	</xs:simpleType>
	
		<xs:simpleType name="LinkID">
	    <xs:annotation>
	      <xs:documentation xml:lang="en-us">
	        A <b>LinkID</b> is an <b>l</b> followed by a number (decimal digits).
	      </xs:documentation>
	    </xs:annotation>
			<xs:restriction base="TimeMLID">
				<xs:pattern value="l\p{Nd}+" />
			</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="Probability">
	    <xs:annotation>
      <xs:documentation xml:lang="en-us">
        The <b>Probability</b> of an annotation is a number between 0.0 and 1.0.
      </xs:documentation>
    </xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="1" />
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="Date">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9X]{4}(-[0-9X]{1,2}(-[0-9X]{1,2})?)?" />			
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Time">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9X]{4}-[0-9X]{1,2}-[0-9X]{1,2})?T(([0-9]{2}(:[0-9]{2}(:[0-9]{2})?)?)|(MO|MI|AF|EV|NI|DT))" />			
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="WeekDate">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9X]{4}-W[0-9X]{1,2}(-([1-7X]|WE))?"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="WeekTime">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9X]{4}-W[0-9X]{1,2}-[1-7X]T(([0-9]{2}(:[0-9]{2}(:[0-9]{2})?)?)|(MO|MI|AF|EV|NI|DT))"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="Season">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9X]{4}-(SP|SU|WI|FA)"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="PartOfYear">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9X]{4}-(H[1-2X]|Q[1-4X])"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="PaPrFu">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PAST_REF"/>
			<xs:enumeration value="PRESENT_REF"/>
			<xs:enumeration value="FUTURE_REF"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="Duration">
		<xs:restriction base="xs:string">
			<xs:pattern value="P((((\p{Nd}+|X{1,2})Y)?((\p{Nd}+|X{1,2})M)?((\p{Nd}+|X{1,2})D)?(T((\p{Nd}+|X{1,2})H)?((\p{Nd}+|X{1,2})M)?((\p{Nd}+|X{1,2})S)?)?)|((\p{Nd}+|X{1,2}))(W|L|E|C|Q))"/>
			<xs:minLength value="3"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="TimeML">

		<xs:unique name="link_id">
			<xs:selector xpath="TLINK|SLINK|ALINK" />
			<xs:field xpath="@lid" />
		</xs:unique>

		<xs:key name="event_id">
			<xs:selector xpath="EVENT" />
			<xs:field xpath="@eid" />
		</xs:key>

		<xs:key name="time_id">
			<xs:selector xpath="TIMEX3" />
			<xs:field xpath="@tid" />
		</xs:key>

		<xs:key name="signal_id">
			<xs:selector xpath="SIGNAL" />
			<xs:field xpath="@sid" />
		</xs:key>

		<xs:key name="event_instance_id">
			<xs:selector xpath="MAKEINSTANCE" />
			<xs:field xpath="@eiid" />
		</xs:key>
		
<!--  	these keyrefs assume that no other (non-TimeML) 
		elements occur within the TimeML root tag.  
		Only use them if non-TimeML tags have been removed.

		<xs:keyref name="event_id_ref_mi" refer="event_id">
			<xs:selector xpath="MAKEINSTANCE" />
			<xs:field xpath="@eventID" />
		</xs:keyref>

		<xs:keyref name="signal_id_ref_mi" refer="signal_id">
			<xs:selector xpath="MAKEINSTANCE" />
			<xs:field xpath="@signalID" />
		</xs:keyref>


		<xs:keyref name="time_id_ref_tx_ati" refer="time_id">
			<xs:selector xpath="TIMEX3" />
			<xs:field xpath="@anchorTimeID" />
		</xs:keyref>

		<xs:keyref name="signal_id_ref_tl" refer="signal_id">
			<xs:selector xpath="TLINK" />
			<xs:field xpath="@signalID" />
		</xs:keyref>

		<xs:keyref name="time_id_ref_tl_ti" refer="time_id">
			<xs:selector xpath="TLINK" />
			<xs:field xpath="@timeID" />
		</xs:keyref>

		<xs:keyref name="time_id_ref_tl_rtt" refer="time_id">
			<xs:selector xpath="TLINK" />
			<xs:field xpath="@relatedToTime" />
		</xs:keyref>

		<xs:keyref name="time_id_ref_tx_bp" refer="time_id">
			<xs:selector xpath="TIMEX3" />
			<xs:field xpath="@beginPoint" />
		</xs:keyref>

		<xs:keyref name="time_id_ref_tx_ep" refer="time_id">
			<xs:selector xpath="TIMEX3" />
			<xs:field xpath="@endPoint" />
		</xs:keyref>

		<xs:keyref name="event_instance_id_ref_tl-eid" refer="event_instance_id">
			<xs:selector xpath="TLINK" />
			<xs:field xpath="@eventInstanceID" />
		</xs:keyref>

		<xs:keyref name="event_instance_id_ref_tl-rte" refer="event_instance_id">
			<xs:selector xpath="TLINK" />
			<xs:field xpath="@relatedToEventInstance" />
		</xs:keyref>

		<xs:keyref name="signal_id_ref_sl" refer="signal_id">
			<xs:selector xpath="SLINK" />
			<xs:field xpath="@signalID" />
		</xs:keyref>

		<xs:keyref name="event_instance_id_ref_sl-eid" refer="event_instance_id">
			<xs:selector xpath="SLINK" />
			<xs:field xpath="@eventInstanceID" />
		</xs:keyref>

		<xs:keyref name="event_instance_id_ref_sl-sei" refer="event_instance_id">
			<xs:selector xpath="SLINK" />
			<xs:field xpath="@subordinatedEventInstance" />
		</xs:keyref>


		<xs:keyref name="signal_id_ref_al" refer="signal_id">
			<xs:selector xpath="ALINK" />
			<xs:field xpath="@signalID" />
		</xs:keyref>

		<xs:keyref name="event_instance_id_ref_al-eid" refer="event_instance_id">
			<xs:selector xpath="ALINK" />
			<xs:field xpath="@eventInstanceID" />
		</xs:keyref>

		<xs:keyref name="event_id_ref_al-rte" refer="event_instance_id">
			<xs:selector xpath="ALINK" />
			<xs:field xpath="@relatedToEventInstance" />
		</xs:keyref>
-->
	</xs:element>


	<xs:element name="EVENT">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
			</xs:sequence> 
			<xs:attribute name="eid" type="EventID" use="required" />

			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="OCCURRENCE" />
						<xs:enumeration value="PERCEPTION" />
						<xs:enumeration value="REPORTING" />
						<xs:enumeration value="ASPECTUAL" />
						<xs:enumeration value="STATE" />
						<xs:enumeration value="I_STATE" />
						<xs:enumeration value="I_ACTION" />
						<xs:enumeration value="MODAL" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			
		</xs:complexType>
	</xs:element>

	<xs:element name="TIMEX3">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
			</xs:sequence> 

			<xs:attribute name="tid" type="TimeID" use="required" />

			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="DATE" />
						<xs:enumeration value="TIME" />
						<xs:enumeration value="DURATION" />
						<xs:enumeration value="SET" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="functionInDocument" default="NONE">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="CREATION_TIME" />
						<xs:enumeration value="EXPIRATION_TIME" />
						<xs:enumeration value="MODIFICATION_TIME" />
						<xs:enumeration value="PUBLICATION_TIME" />
						<xs:enumeration value="RELEASE_TIME" />
						<xs:enumeration value="RECEPTION_TIME" />
						<xs:enumeration value="NONE" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="temporalFunction" type="xs:boolean" default="false" />

			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:union memberTypes="Date Time WeekDate WeekTime Season PartOfYear PaPrFu Duration"/>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="valueFromFunction" type="xs:IDREF" />

			<xs:attribute name="mod">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="BEFORE" />
						<xs:enumeration value="AFTER" />
						<xs:enumeration value="ON_OR_BEFORE" />
						<xs:enumeration value="ON_OR_AFTER" />
						<xs:enumeration value="LESS_THAN" />
						<xs:enumeration value="MORE_THAN" />
						<xs:enumeration value="EQUAL_OR_LESS" />
						<xs:enumeration value="EQUAL_OR_MORE" />
						<xs:enumeration value="START" />
						<xs:enumeration value="MID" />
						<xs:enumeration value="END" />
						<xs:enumeration value="APPROX" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="anchorTimeID" type="TimeID" />

			<xs:attribute name="beginPoint" type="TimeID"/>
			
			<xs:attribute name="endPoint" type="TimeID"/>
			
			<xs:attribute name="quant" type="xs:string"/>

			<xs:attribute name="freq" type="Duration"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="SIGNAL">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
			</xs:sequence> 
			<xs:attribute name="sid" type="SignalID" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="MAKEINSTANCE">
		<xs:complexType>
			<xs:attribute name="eiid" type="EventInstanceID" use="required" />
			<xs:attribute name="eventID" type="EventID" use="required" />
			<xs:attribute name="signalID" type="SignalID" />
			<xs:attribute name="cardinality" type="xs:string" />
			<xs:attribute name="modality" type="xs:string" />
			<xs:attribute name="polarity" default="POS">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="NEG" />
						<xs:enumeration value="POS" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="tense" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="PAST" />
						<xs:enumeration value="PRESENT" />
						<xs:enumeration value="FUTURE" />
						<xs:enumeration value="NONE" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="aspect" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="PROGRESSIVE" />
						<xs:enumeration value="PERFECTIVE" />
						<xs:enumeration value="PERFECTIVE_PROGRESSIVE" />
						<xs:enumeration value="NONE" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="TLINK">
		<xs:complexType>
			<xs:attribute name="lid" type="LinkID" />
			<xs:attribute name="origin" type="xs:string"/>
			<xs:attribute name="eventInstanceID" type="EventInstanceID" />
			<xs:attribute name="timeID" type="TimeID" />
			<xs:attribute name="signalID" type="SignalID" />
			<xs:attribute name="relatedToTime" type="TimeID" />
			<xs:attribute name="relatedToEventInstance" type="EventInstanceID" />
			<xs:attribute name="relType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="BEFORE" />
						<xs:enumeration value="AFTER" />
						<xs:enumeration value="INCLUDES" />
						<xs:enumeration value="IS_INCLUDED" />
						<xs:enumeration value="DURING" />
						<xs:enumeration value="SIMULTANEOUS" />
						<xs:enumeration value="IAFTER" />
						<xs:enumeration value="IBEFORE" />
						<xs:enumeration value="IDENTITY" />
						<xs:enumeration value="BEGINS" />
						<xs:enumeration value="ENDS" />
						<xs:enumeration value="BEGUN_BY" />
						<xs:enumeration value="ENDED_BY" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="magnitude" type="TimeID" />
		</xs:complexType>
	</xs:element>
	<xs:element name="SLINK">
		<xs:complexType>
			<xs:attribute name="lid" type="LinkID" />
			<xs:attribute name="origin" type="xs:string"/>
			<xs:attribute name="eventInstanceID" type="EventInstanceID" />
			<xs:attribute name="subordinatedEventInstance" type="EventInstanceID" use="required" />
			<xs:attribute name="signalID" type="SignalID" />
			<xs:attribute name="relType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MODAL" />
						<xs:enumeration value="NEGATIVE" />
						<xs:enumeration value="EVIDENTIAL" />
						<xs:enumeration value="NEG_EVIDENTIAL" />
						<xs:enumeration value="FACTIVE" />
						<xs:enumeration value="COUNTER_FACTIVE" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="ALINK">
		<xs:complexType>
			<xs:attribute name="lid" type="LinkID" />
			<xs:attribute name="origin" type="xs:string"/>
			<xs:attribute name="eventInstanceID" type="EventInstanceID" use="required" />
			<xs:attribute name="signalID" type="SignalID" />
			<xs:attribute name="relatedToEventInstance" type="EventInstanceID" use="required" />
			<xs:attribute name="relType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="INITIATES" />
						<xs:enumeration value="CULMINATES" />
						<xs:enumeration value="TERMINATES" />
						<xs:enumeration value="CONTINUES" />
						<xs:enumeration value="REINITIATES" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="CONFIDENCE">
		<xs:complexType>
			<xs:attribute name="tagType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="EVENT" />
						<xs:enumeration value="TIMEX3" />
						<xs:enumeration value="SIGNAL" />
						<xs:enumeration value="MAKEINSTANCE" />
						<xs:enumeration value="TLINK" />
						<xs:enumeration value="SLINK" />
						<xs:enumeration value="ALINK" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="tagID" type="TimeMLID" use="required" />
			<xs:attribute name="attributeName">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="anchorTimeID"/>
						<xs:enumeration value="aspect"/>
						<xs:enumeration value="beginPoint"/>
						<xs:enumeration value="cardinality"/>
						<xs:enumeration value="class"/>
						<xs:enumeration value="endPoint"/>
						<xs:enumeration value="eventID"/>
						<xs:enumeration value="eventInstanceID"/>
						<xs:enumeration value="freq"/>
						<xs:enumeration value="functionInDocument"/>
						<xs:enumeration value="lid"/>
						<xs:enumeration value="mod"/>
						<xs:enumeration value="modality"/>
						<xs:enumeration value="negation"/>
						<xs:enumeration value="origin"/>
						<xs:enumeration value="quant"/>
						<xs:enumeration value="relType"/>
						<xs:enumeration value="relatedToEventInstance"/>
						<xs:enumeration value="signalID"/>
						<xs:enumeration value="subordinatedEventInstance"/>
						<xs:enumeration value="temporalFunction"/>
						<xs:enumeration value="tense"/>
						<xs:enumeration value="timeID"/>
						<xs:enumeration value="type"/>
						<xs:enumeration value="value"/>
						<xs:enumeration value="valueFromFunction"/>					
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="confidenceValue" type="Probability" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cnorthwood/ternip/sample_data/timebank/NYT19980206.0466.tml.xml
<?xml version="1.0" ?>
<TimeML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TimeML1.1.xsd" >
<DOCNO> NYT<TIMEX3 tid="t29" type="DATE" temporalFunction="false" functionInDocument="NONE" value="1998-02-06" >19980206</TIMEX3>.0466 </DOCNO>
<DOCTYPE SOURCE="newswire"> NEWS STORY </DOCTYPE>
<DATE_TIME> <TIMEX3 tid="t28" type="TIME" temporalFunction="false" functionInDocument="PUBLICATION_TIME" value="1998-02-06T22:29:00" >02/06/1998 22:29:00</TIMEX3> </DATE_TIME>
<HEADER>
A6982 Cx1f taf-z
u w Cx13  Cx11  BC-CLINTON-CURRIE-NYT LR      02-06 0277
</HEADER>
<BODY>
<SLUG> BC-CLINTON-CURRIE-NYT </SLUG>
<HEADLINE>
STATEMENTS CONCERNING MRS. CURRIE
</HEADLINE>
UR (bl) LR  QL
UR c.1998 N.Y. Times News Service LR  QC   QL

<TEXT>
<s><ENAMEX TYPE="PERSON">WASHINGTON _</ENAMEX> Following are <EVENT eid="e2" class="REPORTING" >statements</EVENT> <EVENT eid="e3" class="REPORTING" >made</EVENT> <TIMEX3 tid="t30" type="DATE" temporalFunction="true" functionInDocument="NONE" value="1998-02-06" anchorTimeID="t28" >Friday</TIMEX3> and <TIMEX3 tid="t31" type="DATE" temporalFunction="true" functionInDocument="NONE" value="1998-02-05" anchorTimeID="t28" >Thursday</TIMEX3>
by <ENAMEX TYPE="PERSON">Lawrence Wechsler, a lawyer for the White <ENAMEX TYPE="ORGANIZATION">House</ENAMEX> secretary</ENAMEX>, <ENAMEX TYPE="PERSON">Betty
Currie</ENAMEX>; the <ENAMEX TYPE="ORGANIZATION">White House</ENAMEX>; <ENAMEX TYPE="PERSON"><ENAMEX TYPE="ORGANIZATION">White House</ENAMEX> spokesman Mike McCurry</ENAMEX>, and
<ENAMEX TYPE="PERSON">President Clinton</ENAMEX> <SIGNAL sid="s154" >in response to</SIGNAL> an <EVENT eid="e43" class="REPORTING" >article</EVENT> in The <ENAMEX TYPE="ORGANIZATION">New York Times</ENAMEX>
<SIGNAL sid="s165" >on</SIGNAL> <TIMEX3 tid="t32" type="DATE" temporalFunction="true" functionInDocument="NONE" value="1998-02-06" anchorTimeID="t28" >Friday</TIMEX3> <SIGNAL sid="s172" >about</SIGNAL> her <EVENT eid="e44" class="REPORTING" >statements</EVENT> <SIGNAL sid="s46" >regarding</SIGNAL> a <EVENT eid="e45" class="OCCURRENCE" >meeting</EVENT> with the
president:
Wechsler <SIGNAL sid="s71" >on</SIGNAL> <TIMEX3 tid="t33" type="DATE" temporalFunction="true" functionInDocument="NONE" value="1998-02-05" anchorTimeID="t28" >Thursday</TIMEX3>
``Without <EVENT eid="e5" class="I_ACTION" >commenting</EVENT> <SIGNAL sid="s215" >on</SIGNAL> the <EVENT eid="e6" class="I_ACTION" >allegations</EVENT> <EVENT eid="e8" class="I_ACTION" >raised</EVENT> <SIGNAL sid="s10" >in</SIGNAL> this <EVENT eid="e9" class="REPORTING" >article</EVENT>,
to the extent that there is any <EVENT eid="e48" class="I_STATE" >implication</EVENT> or <EVENT eid="e49" class="I_ACTION" >suggestion</EVENT> that <ENAMEX TYPE="PERSON">Mrs.
Currie</ENAMEX> was <EVENT eid="e50" class="I_STATE" >aware</EVENT> of any legal or ethical <EVENT eid="e51" class="STATE" >impropriety</EVENT> by anyone,
that <EVENT eid="e52" class="I_STATE" >implication</EVENT> or <EVENT eid="e53" class="I_ACTION" >suggestion</EVENT> is entirely <EVENT eid="e54" class="STATE" >inaccurate</EVENT>.''</s>
<s><ENAMEX TYPE="ORGANIZATION">White House</ENAMEX> <SIGNAL sid="s74" >on</SIGNAL> <TIMEX3 tid="t34" type="DATE" temporalFunction="true" functionInDocument="NONE" value="1998-02-05" anchorTimeID="t28" >Thursday</TIMEX3>
``<SIGNAL sid="s55" >For</SIGNAL> <TIMEX3 tid="t35" type="DURATION" temporalFunction="true" functionInDocument="NONE" value="PXW" anchorTimeID="t34" >the past few weeks</TIMEX3> we 've  been <EVENT eid="e11" class="OCCURRENCE" >subjected</EVENT> to false <EVENT eid="e56" class="REPORTING" >leaks</EVENT>
<EVENT eid="e57" class="I_ACTION" ><EVENT eid="e12" class="OCCURRENCE" >designed</EVENT></EVENT>  to <EVENT eid="e13" class="I_ACTION" >mislead</EVENT> both reporters and the American public.</s> <s>We're <SIGNAL sid="s15" >not</SIGNAL> going  to <EVENT eid="e16" class="I_ACTION" >dignify</EVENT> the <TIMEX3 tid="t36" type="DATE" temporalFunction="true" functionInDocument="NONE" value="PAST_REF" anchorTimeID="t34" >latest</TIMEX3> false <EVENT eid="e58" class="REPORTING" >leak</EVENT> with a <EVENT eid="e59" class="I_ACTION" >response</EVENT>.''</s>
<s>McCurry <SIGNAL sid="s75" >on</SIGNAL> <TIMEX3 tid="t37" type="DATE" temporalFunction="true" functionInDocument="NONE" value="1998-02-06" anchorTimeID="t28" >Friday</TIMEX3>
``I <EVENT eid="e17" class="I_ACTION" >want</EVENT> to be absolutely <EVENT eid="e60" class="I_STATE" >clear</EVENT>, to the extent there is any
<EVENT eid="e61" class="I_STATE" >implication</EVENT> or the slightest <EVENT eid="e62" class="I_ACTION" >suggestion</EVENT> that <ENAMEX TYPE="PERSON">Mrs. Currie</ENAMEX> <EVENT eid="e18" class="I_STATE" >believes</EVENT>
that the President or anyone else <EVENT eid="e19" class="I_ACTION" >tried</EVENT>  to <EVENT eid="e20" class="I_ACTION" >influence</EVENT> her
<EVENT eid="e63" class="I_STATE" >recollection</EVENT>, that is absolutely <EVENT eid="e64" class="STATE" >false</EVENT> and a <EVENT eid="e65" class="REPORTING" >mischaracterization</EVENT> of
the facts.</s> <s>I  am <EVENT eid="e21" class="I_STATE" >shocked</EVENT> and <EVENT eid="e66" class="I_STATE" >dismayed</EVENT> by the numerous <EVENT eid="e67" class="REPORTING" >leaks</EVENT>
<SIGNAL sid="s68" >regarding</SIGNAL> <ENAMEX TYPE="PERSON">Mrs. Currie</ENAMEX>'s grand jury <EVENT eid="e69" class="REPORTING" >testimony</EVENT>.''</s>
<s><ENAMEX TYPE="PERSON">Clinton</ENAMEX> <SIGNAL sid="s76" >on</SIGNAL> <TIMEX3 tid="t38" type="DATE" temporalFunction="true" functionInDocument="NONE" value="1998-02-06" anchorTimeID="t28" >Friday</TIMEX3>.</s>
<s>``Once again, I <SIGNAL sid="s77" >never</SIGNAL> <EVENT eid="e23" class="I_ACTION" >asked</EVENT> anybody  to <EVENT eid="e24" class="I_ACTION" >do</EVENT> anything but <EVENT eid="e25" class="I_ACTION" >tell</EVENT> the
truth.</s> <s>I <EVENT eid="e26" class="I_STATE" >know</EVENT> <SIGNAL sid="s78" >about</SIGNAL> the <EVENT eid="e79" class="REPORTING" >stories</EVENT> <TIMEX3 tid="t39" type="DATE" temporalFunction="true" functionInDocument="NONE" value="1998-02-06" anchorTimeID="t38" >today</TIMEX3>.</s> <s>I was <EVENT eid="e80" class="I_STATE" >pleased</EVENT> that <ENAMEX TYPE="PERSON">Ms.
Currie</ENAMEX>'s lawyers <EVENT eid="e27" class="I_ACTION" >stated</EVENT> unambiguously <TIMEX3 tid="t40" type="TIME" temporalFunction="true" functionInDocument="NONE" value="1998-02-06TMO" anchorTimeID="t38" >this morning</TIMEX3> _ unambiguously
_ that she's <SIGNAL sid="s82" >not</SIGNAL> <EVENT eid="e81" class="I_STATE" >aware</EVENT> of any unethical <EVENT eid="e83" class="OCCURRENCE" >conduct</EVENT>.</s>
</TEXT>
</BODY>
<TRAILER>
<s>NYT-<TIMEX3 tid="t41" type="TIME" temporalFunction="false" functionInDocument="PUBLICATION_TIME" value="1998-02-06T22:29" >02-06-98 2229EST</TIMEX3></s>
</TRAILER>

<MAKEINSTANCE aspect="NONE" eiid="ei509" tense="PRESENT" eventID="e2" />
<MAKEINSTANCE aspect="NONE" eiid="ei510" tense="PAST" eventID="e3" />
<MAKEINSTANCE aspect="NONE" eiid="ei511" tense="NONE" eventID="e43" />
<MAKEINSTANCE aspect="NONE" eiid="ei512" tense="NONE" eventID="e44" />
<MAKEINSTANCE aspect="NONE" eiid="ei513" tense="NONE" eventID="e45" />
<MAKEINSTANCE aspect="PROGRESSIVE" eiid="ei514" tense="NONE" eventID="e5" />
<MAKEINSTANCE aspect="NONE" eiid="ei515" tense="NONE" eventID="e6" />
<MAKEINSTANCE aspect="PERFECTIVE" eiid="ei516" tense="NONE" eventID="e8" />
<MAKEINSTANCE aspect="NONE" eiid="ei517" tense="NONE" eventID="e9" />
<MAKEINSTANCE aspect="NONE" eiid="ei518" tense="NONE" eventID="e48" />
<MAKEINSTANCE aspect="NONE" eiid="ei519" tense="NONE" eventID="e49" />
<MAKEINSTANCE aspect="NONE" eiid="ei520" tense="PAST" eventID="e50" />
<MAKEINSTANCE aspect="NONE" eiid="ei521" tense="NONE" eventID="e51" />
<MAKEINSTANCE aspect="NONE" eiid="ei522" tense="NONE" eventID="e52" />
<MAKEINSTANCE aspect="NONE" eiid="ei523" tense="NONE" eventID="e53" />
<MAKEINSTANCE aspect="NONE" eiid="ei524" tense="NONE" eventID="e54" />
<MAKEINSTANCE aspect="PERFECTIVE" eiid="ei525" tense="PRESENT" eventID="e11" />
<MAKEINSTANCE aspect="NONE" eiid="ei526" tense="NONE" eventID="e56" />
<MAKEINSTANCE aspect="NONE" eiid="ei527" tense="NONE" eventID="e57" />
<MAKEINSTANCE aspect="PERFECTIVE" eiid="ei528" tense="NONE" eventID="e12" />
<MAKEINSTANCE aspect="NONE" eiid="ei529" tense="NONE" eventID="e13" />
<MAKEINSTANCE aspect="NONE" eiid="ei530" tense="FUTURE" eventID="e16" />
<MAKEINSTANCE aspect="NONE" eiid="ei531" tense="NONE" eventID="e58" />
<MAKEINSTANCE aspect="NONE" eiid="ei532" tense="NONE" eventID="e59" />
<MAKEINSTANCE aspect="NONE" eiid="ei533" tense="PRESENT" eventID="e17" />
<MAKEINSTANCE aspect="NONE" eiid="ei534" tense="NONE" eventID="e60" />
<MAKEINSTANCE aspect="NONE" eiid="ei535" tense="NONE" eventID="e61" />
<MAKEINSTANCE aspect="NONE" eiid="ei536" tense="NONE" eventID="e62" />
<MAKEINSTANCE aspect="NONE" eiid="ei537" tense="PRESENT" eventID="e18" />
<MAKEINSTANCE aspect="NONE" eiid="ei538" tense="PAST" eventID="e19" />
<MAKEINSTANCE aspect="NONE" eiid="ei539" tense="NONE" eventID="e20" />
<MAKEINSTANCE aspect="NONE" eiid="ei540" tense="NONE" eventID="e63" />
<MAKEINSTANCE aspect="NONE" eiid="ei541" tense="NONE" eventID="e64" />
<MAKEINSTANCE aspect="NONE" eiid="ei542" tense="NONE" eventID="e65" />
<MAKEINSTANCE aspect="NONE" eiid="ei543" tense="PRESENT" eventID="e21" />
<MAKEINSTANCE aspect="NONE" eiid="ei544" tense="PRESENT" eventID="e66" />
<MAKEINSTANCE aspect="NONE" eiid="ei545" tense="NONE" eventID="e67" />
<MAKEINSTANCE aspect="NONE" eiid="ei546" tense="NONE" eventID="e69" />
<MAKEINSTANCE aspect="NONE" eiid="ei547" tense="PAST" eventID="e23" />
<MAKEINSTANCE aspect="NONE" eiid="ei548" tense="NONE" eventID="e24" />
<MAKEINSTANCE aspect="NONE" eiid="ei549" tense="NONE" eventID="e25" />
<MAKEINSTANCE aspect="NONE" eiid="ei550" tense="PRESENT" eventID="e26" />
